---
date: '`r invisible( Sys.setlocale("LC_TIME", "C") ); format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    number_sections: yes
    theme: united
    toc: yes
    toc_depth: 5
    toc_float: yes
    self_contained: yes
title: "Report species preliminary conservation assessment"
---

```{r setup, include=FALSE}
RUN <- TRUE
knitr::opts_chunk$set(echo = FALSE, comment = NA, fig.align = "center", include = RUN)
library(knitr)
```



# Preliminary Conservation Assessment of `r list.names$df[as.numeric(input$name_chosen)]`

```{r echo = FALSE}
# select the column we need
selectColumn <- c(
  input$sel_taxa, input$sel_genus, input$sel_species_epiteth, input$sel_authors,
  input$sel_rank, 
  input$sel_lower_infra, input$sel_lower_infra_authors, input$sel_LONG,
  "taxa"
)
selectedColumn <- selectColumn != "<unselected>"

dataset <- original.dataset$df
  # readr::read_csv(input$file_DATASET$datapath,
  #                     locale = readr::locale(encoding = stringi::stri_enc_get()))

Name <- list.names$df[as.numeric(input$name_chosen)]
name_quo <- dplyr::enquo(Name)
    
    # print(selectedColumn)

dataset <-
  dataset %>%
  dplyr::select(selectColumn[selectedColumn]) %>%
  dplyr::filter(taxa==!!name_quo)


# data <- setDT(inv()[, selectColumn[selectedColumn]])
# setnames(data, names(data), c(
#   "plot", "genus", "species","D",
#   "WD", 
#   "H", "longitude", "latitude"
# )[selectedColumn])

# print(dataset)
kable(head(dataset), digits = 3, caption = "Head of the data")



# print(selectedColumn)
```

```{r, echo=FALSE}
map_types <- c("Esri.NatGeoWorldMap", "Esri.WorldImagery", "OpenStreetMap.DE",
                       "Esri.WorldPhysical")
dataset_circle_select <-
        original.dataset.accuracy$df %>%
        filter(taxa==!!name_quo)

dataset_sf <-
        sf::st_as_sf(original.dataset$df %>% filter(taxa==!!name_quo, !is.na(!!rlang::sym(input$sel_LAT)),!is.na(!!rlang::sym(input$sel_LONG))), coords = c(input$sel_LONG, input$sel_LAT), crs = 4326)


mapview::mapview(dataset_circle_select, map.types = map_types,
                           col.regions = "red", alpha.regions = 0.1, legend =FALSE, viewer.suppress=F)

# +
# mapview::mapview(dataset_sf, col.regions = "red", map.types = map_types, legend =FALSE, viewer.suppress=T)

# +
#              +
#             mapview::mapview(eoo_poly_full, col.regions = "blue", alpha.regions = 0.05, map.types = map_types, legend =FALSE, viewer.suppress=T) +
#             mapview::mapview(eoo_poly_left, col.regions = "red", alpha.regions = 0.1, map.types = map_types, legend =FALSE, viewer.suppress=T) +
#             mapview::mapview(protected_areas_cropped$df, col.regions = "green", alpha.regions = 0.3, map.types = map_types, legend = TRUE, layer.name = "Protected areas", viewer.suppress=T) +
#             mapview::mapview(logging_concessions_CA_cropped$df, col.regions = "blueviolet", lwd=2, alpha.regions = 0.2, map.types = map_types, legend = TRUE, layer.name = "Logging concessions", viewer.suppress=T) +
#             mapview::mapview(raster_mayaux_cropped$df, col.regions = "red", alpha.regions = alpha_raster_mayaux$df, map.types = map_types, legend =FALSE, layer.name = "mayaux human dominated land cover", viewer.suppress=T)  +
#             mapview::mapview(raster_hansen_cropped$df, col.regions = "purple", alpha.regions = alpha_raster_deforest$df, map.types = map_types, legend =FALSE, layer.name = "proportion of forest cover loss", viewer.suppress=T)  +
#             mapview::mapview(mineral_cropped$df, col.regions = "black", alpha.regions = 0.3, map.types = map_types, legend = TRUE, layer.name = "mineral deposit", viewer.suppress=T)# pal(100), at = seq(0, 1, 0.1)

```

